checks:
  doNotAutoAddDefaults: true
  include:
    - dangling-service
    - dangling-networkpolicy
    - default-service-account
    - deprecated-service-account-field
    - docker-sock
    - drop-net-raw-capability
    - host-ipc
    - host-network
    - host-pid
    - invalid-target-ports
    - latest-tag
    - liveness-port
    - mismatching-selector
    - no-extensions-v1beta
    - no-read-only-root-fs
    - no-rolling-update-strategy
    - non-isolated-pod
    - non-existent-service-account
    - privilege-escalation-container
    - privileged-container
    - readiness-port
    - sensitive-host-mounts
    - startup-port
    - unsafe-proc-mount
    - unsafe-sysctls
    - unset-cpu-requirements
    - unset-memory-requirements
    - writable-host-mount
